### ISSUE TITLE
user mysql exporter is not created in image: sebs42/mariadb:10.4.12-bionic

### ISSUE THREAD

**Issue by ldangeard-orange** [Orange-OpenSource/galera-operator#5]
In image 10.4.12, user export creation is missing in docker-entrypoint.sh

We need to create
`CREATE USER 'exporter'@'localhost' IDENTIFIED BY '${EXPORTER_PASSWORD}' WITH MAX_USER_CONNECTIONS 3;
GRANT PROCESS,REPLICATION CLIENT,SELECT ON *.* TO 'exporter'@'localhost';`
and update documentation https://github.com/Orange-OpenSource/galera-operator/blob/master/doc/design/galera_images.md

**Comment by ldangeard-orange** [comment]
Solution is to drop and create user exporter (with the last password) in my.cnf.

**Comment by sebs42** [comment]
mariadb images are provided as example, if you want to create additional users to follow design rules of your division, you are free to do that. It is also recommended to not used example images as it because there are very simple and basic

**Comment by ldangeard-orange** [comment]
it's not an additional user , this user is used by prometheus mysql exporter to connect to mariadb
