### ISSUE TITLE
Use the new image prom/mysql-exporter image: v0.12.1

### ISSUE THREAD

**Issue by plafosse-orange** [Orange-OpenSource/galera-operator#8]
With version v0.11.0 we detect in the metric logs many connection problems to the MariaDB instance. This results in a non-rise of the metrics at Promotheus.
We no longer have these problems with image v0.12.1

**Comment by sebs42** [comment]
Example have been changed, but remember, it is an example, not a recommandation or something forced by the galleria operator design. You are free to use your own images and the versions that fit your needs.
